version: '3.4'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
      POSTGRES_DB: citybike
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
  blazor:
    build:
      context: ./cityBikeApp
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - db
      